class DropShipOrderStatus:
    STARTED = 0
    PURCHASED = 1
    ACKNOWLEDGED = 2
    CONFIRMED = 3
    PARTIALLY_SHIPPED = 4
    SHIPPED = 5
    DELAYED = 6
    BACKORDERED = 7
    CANCELED_US = 8
    CANCELED_OOS = 9
    CANCELED_OK = 10
    CANCELED_BAD = 11
    DELIVERED = 12
    CANCELLATION_REVIEW = 13
    PROCESSING_STATUS = 14
