default_language_version:
  python: python3.8

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -  id: end-of-file-fixer
    -  id: trailing-whitespace
    -  id: debug-statements
    -  id: no-commit-to-branch

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        pass_filenames: false
        verbose: true
        always_run: true
