import os


BUYBOT_USERNAME = os.environ.get("BUYBOT_USERNAME")
BUYBOT_PASSWORD = os.environ.get("BUYBOT_PASSWORD")

BUY_PROXIES_USERNAME = os.environ.get("BUY_PROXIES_USERNAME")
BUY_PROXIES_PASSWORD = os.environ.get("BUY_PROXIES_PASSWORD")
LUMINATI_DOMAIN = os.environ.get("LUMINATI_DOMAIN")
LUMINATI_USERNAME = os.environ.get("LUMINATI_USERNAME")
LUMINATI_PASSWORD = os.environ.get("LUMINATI_PASSWORD")

WALMART_PASSWORD = os.environ.get("WALMART_PASSWORD")
WALMART_OLD_PASSWORDS = os.environ.get("WALMART_OLD_PASSWORDS")
WALMART_OLD_PASSWORDS = WALMART_OLD_PASSWORDS.split(",")
WALMART_SELF_RESOLVE_CAPTCHA = True
